### ISSUE TITLE
A Step Further: require

### ISSUE THREAD

**Issue by kaendfinger** [seaneagan/which.dart#2]
I wrote this code many times before, very useful when working with CLI tools. I also wrote something like this:

```dart
require(List<String> tools) async {
  for (var tool in tools) {
    var path = await which(tool, orElse: () => null);
    if (path == null) {
      print("ERROR: the tool '${tool}' is required, but was not found.");
      /* Possibly even give tips on how to install it */
      exit(1);
    }
  }
}
```

This is my simplified version. I even had where a tool in the list could be named `this|that` so that you can require either or.

**Comment by seaneagan** [comment]
`which` and `whichSync` already throw a similar error by default if you don't include orElse, so it's pretty easy to do already:

```dart
try {
  ['git', 'node', 'npm'].forEach(which);
} catch (e) {
  print(e);
  exit(1);
}
```

**Comment by kaendfinger** [comment]
Oh nice, thanks :)

**Comment by kaendfinger** [comment]
@seaneagan: Does the error contain info about which tool wasn't found?

**Comment by seaneagan** [comment]
It does, something like "Command not found: $command".

**Comment by kaendfinger** [comment]
Nice.
