### ISSUE TITLE
which has lots of deps

### ISSUE THREAD

**Issue by devoncarew** [seaneagan/which.dart#3]
`which` is awesome! It makes me want to think of a who's on first joke, with `what` and `how` packages.

I switched over to using it in a package instead of shelling out. I definitely felt better about it - shelling out always seems unreliable (and I didn't have support for window to boot).

One thing I noticed was that that package transitive deps doubled. We gained `unscripted`, and `when`, and I think a few other that they referenced. Any thoughts on trimming the deps a bit? I try and be careful about how many package I bring in - each one can lead to version conflicts, for me or for people who import me.

**Comment by seaneagan** [comment]
Thanks for the report!  This is why https://dartbug.com/22054 would be nice.

Anyways, these deps are now gone:

- ansicolor 0.0.9
- args 0.12.2+1
- collection 1.1.0
- logging 0.9.3
- mockable_filesystem 0.0.3
- quiver 0.20.0
- supports_color 0.1.1
- unscripted 0.5.2+1

**Comment by devoncarew** [comment]
Yup, I dropped 5 deps:
```
- ansicolor 0.0.9
- logging 0.9.3
- mockable_filesystem 0.0.3
- supports_color 0.1.1
- unscripted 0.5.2+1
```

Thanks!

**Comment by kaendfinger** [comment]
Oh I see, thanks.
